### ISSUE TITLE
Repeated items in last page

### ISSUE THREAD

**Issue by diego1686** [deltaepsilon/firebase-paginator#11]
Hi! I have an issue using infinite pagination. If the number of items per page is minor than the total records and isn't a multiple of it, the last page has always repeated items. For example:

- Total items = 10, items per page = 2 => no problem here, items per page is minor than the total but it's a multiple. 5 pages in total.

- Total items = 11, items per page = 2 => 6 pages in total, but the last one has two items instead of one. The repeated item also appears in the page 5. In this case the last page is always full and this is an evident issue if I'm using big pages... For example, if I have 1001 records, and pages of 100, the last page is going to have 100 records too, with 99 records repeated!

**Comment by deltaepsilon** [comment]
Oh no! Thanks for reporting this. I'll take a look at it soon. 

I thought I had test coverage for this, the problem could be on my end.

If it turns out that my test coverage is strong, that's going to indicate that the problem is on your end.

**Comment by diego1686** [comment]
@deltaepsilon here is a more detailed example about this issue. Please let me know if there is something I'm doing wrong. Suppose I have this on Firebase:

<img width="150" alt="firebase" src="https://user-images.githubusercontent.com/1087468/26929569-69d12a9c-4c5a-11e7-9f76-57f668297e3f.png">

My code looks like this:

```javascript
        var options = {
            pageSize: 2
         };

        const ref = admin.database().ref('/firebasePaginator');
        var paginator = new FirebasePaginator(ref, options);
        var isLastPage = false;

        paginator.on('previous', function(){
          collection = paginator.collection;
          console.log("previous event", collection);
          if (isLastPage)
              done();
          else
            paginator.previous();
        });

        paginator.on('ready', function(){
          collection = paginator.collection;
          console.log("ready event", collection);
          paginator.previous();
        });


        paginator.on('isLastPage', function(){
          console.log("last page event");
          isLastPage = true;
        });
      });
```

And this is the output I got:

```
ready event { '4': 'test', '5': 'test' }
previous event { '2': 'test', '3': 'test' }
last page event
previous event { '1': 'test', '2': 'test' }
```

The item number 2 is repeated in the last page

**Comment by deltaepsilon** [comment]
I just wrote tests for paginating a 100-record collection with a page size of 30. It correctly paginates 100 to 71, 70 to 41, 40 to 11 and 10 to 1. I can't replicate the duplication.

Let me know if/when you figure this one out!

**Comment by diego1686** [comment]
@deltaepsilon Do you see something wrong in the code above? I spent the last three days trying to resolve this issue in different ways (using promises, doing it recursively) and I always get the same result

**Comment by deltaepsilon** [comment]
This is kind of hilarious. I sat on your issue for six days and finally addressed it this morning just before I checked my email. Now I see that you added this extra detail just before I responded :)

I'll try to figure this out now.

**Comment by deltaepsilon** [comment]
Got it!

See my latest version v1.1.0 on commit [f8eef72](https://github.com/deltaepsilon/firebase-paginator/commit/f8eef726b047c2203e8f1e7c0216ceb4d9c456c3)

It turns out that I intended the behavior that you're seeing. I can't remember why, but it made sense at the time to always return the full pageSize if possible.

Once you've upgraded to v1.1.0, just set ```retainLastPage: true``` in your options to allow the short last page.

Thanks for bringing this up, and let me know if it gives you any more trouble!

**Comment by diego1686** [comment]
@deltaepsilon great!! Thank you!

**Comment by deltaepsilon** [comment]
@diego1686 Sorry it took so long 😦 

But better late than never? 😄

**Comment by diego1686** [comment]
@deltaepsilon the retainLastPage option did the trick, but now the isLastPage event is never fired. I'm using the same example above, what am I doing wrong?

**Comment by deltaepsilon** [comment]
Thanks for the heads up! I just fixed it with [bd287ed](https://github.com/deltaepsilon/firebase-paginator/commit/bd287ed8eb820455a2537f6036a82f0d8f8f4724)

**Comment by diego1686** [comment]
@deltaepsilon great! thanks a lot

**Comment by hcyildirim** [comment]
@deltaepsilon Im having the same issue. Here is my options:

```
const options = {
    pageSize: 16,
    finite: false,
    retainLastPage: true,
  };

```
