### ISSUE TITLE
TypeError: FirebasePaginator is not a constructor

### ISSUE THREAD

**Issue by valorloff** [deltaepsilon/firebase-paginator#12]
Hi!
Thank for this job!
I'm trying include paginator to isomorphic react-firebase (latest 16 and 4.6.2) app like [this](https://github.com/firebase/functions-samples/tree/master/isomorphic-react-app)
```
// functions/firebase-database.js:
const FirebasePaginator = require('firebase-paginator')
// src/containers/App.jsx:
const FirebasePaginator = typeof window !== 'undefined' ? window.FirebasePaginator: undefined;
```
## Expected outcome
get basic functionality with default options:
```
const paginator = new FirebasePaginator(firebase.database().ref('/employees').orderByChild('level'));
const getAllEmployees = () => {
  return paginator.once('value').then(snap => {
    return {employees: snap.val()};
  });
};
```
## Actual outcome

`TypeError: FirebasePaginator is not a constructor`

**Comment by deltaepsilon** [comment]
I didn't build FirebasePaginator for ES2015 imports. I built it the old
fashioned way... to get added to a script tag.

So the script tag on your page will get it added to the window object. Also
try importing just the file path and not assigning it to a variable... then
access it off of window.

Or fork the project, get it working and send me a pull request!

**Comment by deltaepsilon** [comment]
I've finally gotten deep enough into Babel to go back and repair this. Sorry it took so long!

3c053de8e61be4378f8fcef4fb36aa7f206c6505
