### ISSUE TITLE
Uncaught TypeError: _firebasePaginator2.default is not a constructor

### ISSUE THREAD

**Issue by distravantari** [deltaepsilon/firebase-paginator#13]
https://github.com/deltaepsilon/firebase-paginator/blob/d157beae0b37baf88c4addac072ccd7c5f09a522/firebase-paginator.js#L296

I got "Uncaught TypeError: _firebasePaginator2.default is not a constructor" because of this line I guess, I change it to "(!isBrowser)" and it works

**Comment by deltaepsilon** [comment]
Haha. Good fix!

I built firebase-paginator.js to be added to the page with a script tag. I built it long before I started using Babel and ES2015 modules.

It looks like defaulting to the Node.js export was all that Babel needed to be happy.

**Comment by deltaepsilon** [comment]
I've published v1.1.2 to NPM. Let me know if the export is still causing you trouble!

3c053de8e61be4378f8fcef4fb36aa7f206c6505
