### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by s1lviu** [deltaepsilon/firebase-paginator#18]
Hi!
On node v8.11.1 I receive this:
<img src="https://i.imgur.com/a98TArl.png">

**Comment by deltaepsilon** [comment]
That's an es6 import, which means that you'll need to ingest this file through Babel. You can do a one-time compilation if you're not using any other es6 in your project. If you're using es6 already, just make sure that you're importing this module into another es6 module that's being parsed by Babel and you should be fine.
