### ISSUE TITLE
module needlessly pulls in a ton of unrelated bower modules(polymer,webcomponents) as dependencies

### ISSUE THREAD

**Issue by r3wt** [deltaepsilon/firebase-paginator#6]
@deltaepsilon 
will you fix it? Or moreover, if you get a PR will you merge it?

**Comment by deltaepsilon** [comment]
Thanks for that. I rushed this module out the door and didn't test the bower or npm installations nearly enough. 

I took care of the issue :)

**Comment by r3wt** [comment]
@deltaepsilon apparently not, it still installs the unrelated dependencies

**Comment by deltaepsilon** [comment]
@r3wt Oops! I was focused on NPM. I spaced Bower entirely. I just moved those spare bower deps to devDependencies and pushed the update. Looks better now with both package managers.

Thanks for the heads up!
